plugins {
    id 'java'
}

group = 'dev.portfolio'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Lombok
    compileOnly 'org.projectlombok:lombok:1.18.48'
    annotationProcessor 'org.projectlombok:lombok:1.18.48'
    testCompileOnly 'org.projectlombok:lombok:1.18.48'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.48'

    // Log4j2
    implementation platform('org.apache.logging.log4j:log4j-bom:2.26.1')
    implementation 'org.apache.logging.log4j:log4j-api'
    runtimeOnly 'org.apache.logging.log4j:log4j-core'

    // DB 관련
    // https://mvnrepository.com/artifact/org.mariadb.jdbc/mariadb-java-client
//    implementation 'org.mariadb.jdbc:mariadb-java-client:3.5.3'
}

test {
    useJUnitPlatform()
}